from enum import StrEnum


class ProjectStatus(StrEnum):
    PREDIO_RECIBIDO = "PREDIO_RECIBIDO"
    PREDIO_REGISTRADO = "PREDIO_REGISTRADO"
    FACTIBILIDAD_EN_REVISION = "FACTIBILIDAD_EN_REVISION"
    PENDIENTE_RESPUESTA_WIN = "PENDIENTE_RESPUESTA_WIN"
    PREDIO_APROBADO = "PREDIO_APROBADO"
    PREDIO_RECHAZADO = "PREDIO_RECHAZADO"
    PREDIO_OBSERVADO = "PREDIO_OBSERVADO"
    ASIGNADO_A_CUADRILLA = "ASIGNADO_A_CUADRILLA"
    EN_EJECUCION = "EN_EJECUCION"
    PENDIENTE_REVISION = "PENDIENTE_REVISION"
    OBSERVADO = "OBSERVADO"
    APROBADO = "APROBADO"
    LIQUIDADO = "LIQUIDADO"


class EvidenceCategory(StrEnum):
    CHARLA_5_MIN = "CHARLA_5_MIN"
    ATS = "ATS"
    FACHADA = "FACHADA"
    INGRESO_COMUN = "INGRESO_COMUN"
    LATERAL_DERECHA = "LATERAL_DERECHA"
    LATERAL_IZQUIERDA = "LATERAL_IZQUIERDA"
    NODO = "NODO"
    MUFA = "MUFA"
    NAP = "NAP"
    PUNTA = "PUNTA"
    RESERVA = "RESERVA"
    RECORRIDO_POSTE = "RECORRIDO_POSTE"
    OC_MATERIAL = "OC_MATERIAL"
    OC_CANALIZACION = "OC_CANALIZACION"
    OC_CAMARA = "OC_CAMARA"
    OC_REPOSICION = "OC_REPOSICION"
    OTRO = "OTRO"


class ProjectType(StrEnum):
    PEXT = "PEXT"
    OC = "OC"
    MIXTO = "MIXTO"
